import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Midhun Raj - The story</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Midhun Raj
        </h1>

       
      </main>

      <footer className={styles.footer}>
        Powered by Rajappan The Hacker
      </footer>
    </div>
  )
}
